name: CD compute

on:
  push:
    branches:
      - 'prod'
      - 'preprod'

  workflow_dispatch:
    inputs:
      run_tests:
        type: choice
        required: false
        default: 'yes'
        description: Run tests?
        options:
          - 'yes'
          - 'no'

  workflow_call:

jobs:
  deploy-api:
    if: ${{ github.ref_name == 'prod' || github.ref_name == 'preprod' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      AWS_REGION: eu-west-3
      CODEARTIFACT_AUTH_TOKEN : `aws codeartifact get-authorization-token --domain harena --domain-owner 182574566954 --region eu-west-3 --query authorizationToken --output text`

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - uses: hei-school/aws-credentials-setter@v1.0.3
        with:
          secrets: ${{ toJSON(secrets) }}
          region: ${{ env.AWS_REGION }}

      - name: Disable tests
        if: ${{ github.event.inputs.run_tests == 'no' }}
        run: |
          printf "tasks.named('test').configure {\n    enabled = false\n}" >> build.gradle

      - run: sam build

      - name: Deploy application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ github.ref_name }}-compute-harena --capabilities CAPABILITY_IAM --parameter-overrides Env=${{ github.ref_name }} --resolve-s3 --tags app=harena env=${{ github.ref_name }} user:poja=harena

